from flask import Flask, render_template, request, jsonify
import random

app = Flask(__name__)

def obter_mensagem_positiva(nome):
    mensagens_positivas = [
        f"Olá, {nome}! Você é incrível.",
        f"{nome}, acredite no seu potencial. Você é capaz de grandes coisas.",
        f"Continue assim, {nome}! O mundo precisa da sua positividade.",
        f"Você é incrível, {nome}! Continue brilhando.",
        f"Não esqueça, {nome}, o mundo é melhor com você nele.",
        f"Sua presença faz a diferença, {nome}.",
        f"Continue a acreditar em si mesmo, {nome}.",
        f"O que você faz é importante, {nome}.",
        f"Seu potencial é ilimitado, {nome}.",
        f"Cada novo dia é uma oportunidade para crescer, {nome}.",
        f"Você é mais forte do que pensa, {nome}.",
        f"Sua determinação inspira, {nome}.",
        f"Suas qualidades são únicas, {nome}.",
        f"A vida é um presente, {nome}. Aproveite cada momento.",
        f"Seja gentil consigo mesmo, {nome}. Você merece amor e compreensão.",
        f"O progresso, não a perfeição, é o que realmente importa, {nome}.",
        f"Você está exatamente onde precisa estar, {nome}.",
        f"Não subestime o impacto positivo que você pode ter, {nome}.",
        f"Cada passo que você dá é um passo na direção certa, {nome}.",
        f"Sua jornada é única e valiosa, {nome}.",
        f"Você é capaz de superar qualquer desafio, {nome}.",
        f"A positividade está dentro de você, {nome}. Cultive-a.",
        f"Acredite nas suas habilidades, {nome}. Você é capaz de coisas incríveis.",
        f"A gratidão transforma o que temos em suficiente, {nome}.",
        f"Cada obstáculo é uma oportunidade para crescer, {nome}.",
        f"Você é resiliente, {nome}. Continue avançando.",
        f"Seu sorriso ilumina o dia de muitas pessoas, {nome}.",
        f"A vida é cheia de possibilidades, {nome}. Explore-as com entusiasmo.",
        f"Você é uma fonte de inspiração, {nome}.",
        f"Não há ninguém como você, {nome}. Isso é algo maravilhoso.",
        f"A autenticidade é a sua maior força, {nome}.",
        f"Seu coração é generoso, {nome}. Continue espalhando bondade.",
        f"A jornada é tão importante quanto o destino, {nome}.",
        f"Você é amado e apreciado, {nome}.",
        f"A beleza está em ser você mesmo, {nome}.",
        f"Cada dia é uma oportunidade para aprender e crescer, {nome}.",
        f"Sua presença é um presente para o mundo, {nome}.",
        f"A verdadeira beleza vem de dentro, {nome}.",
        f"Você é único e valioso, {nome}.",
        f"O amor-próprio é a base para uma vida plena, {nome}.",
        f"Você merece todo o sucesso e felicidade, {nome}.",
        f"A alegria está nas pequenas coisas, {nome}.",
        f"Você é capaz de superar desafios com graça, {nome}.",
        f"A vida é cheia de possibilidades emocionantes, {nome}.",
        f"Acredite na sua força interior, {nome}.",
        f"Sua jornada é cheia de potencial, {nome}.",
        f"Você é mais resiliente do que pensa, {nome}.",
        f"Cada dia é uma nova oportunidade para ser o melhor de si mesmo, {nome}.",
        f"A autenticidade é a sua maior superpotência, {nome}.",
        f"Você é uma obra de arte em constante evolução, {nome}.",
        f"Suas experiências moldam quem você é, {nome}.",
        f"Seu coração compassivo torna o mundo mais bonito, {nome}.",
        f"Sua luz brilha intensamente, {nome}.",
        f"A verdadeira beleza emana de sua autenticidade, {nome}.",
        f"Aprecie o processo de se tornar a melhor versão de si mesmo, {nome}.",
        f"Cada passo que você dá é um passo na direção certa, {nome}.",
        f"Você é digno de todas as coisas boas, {nome}.",
        f"Cada dia é uma nova página em sua história, {nome}.",
        f"A vida é uma jornada incrível, {nome}.",
        f"Você é forte, resiliente e capaz, {nome}.",
        f"Agradeça pelo que você é agora e antecipe o que você se tornará, {nome}.",
        f"Sua presença é um presente para o mundo, {nome}.",
        f"Abrace o processo de crescimento, {nome}.",
        f"Você é capaz de alcançar alturas incríveis, {nome}.",
        f"A vida está cheia de possibilidades, {nome}.",
        f"Você é um ser único e valioso, {nome}.",
        f"A autenticidade é sua maior fortaleza, {nome}.",
        f"Seu coração generoso torna o mundo mais brilhante, {nome}.",
        f"Sua jornada é cheia de potencial, {nome}.",
        f"Você é mais resiliente do que imagina, {nome}.",
        f"A beleza da vida está nas pequenas coisas, {nome}.",
        f"Você é capaz de superar desafios com graça, {nome}.",
        f"A vida é cheia de possibilidades emocionantes, {nome}.",
        f"Acredite em sua força interior, {nome}.",
        f"Sua jornada está cheia de potencial, {nome}.",
        f"Você é mais resiliente do que pensa, {nome}.",
        f"Cada dia é uma nova oportunidade para ser o melhor de si mesmo, {nome}.",
        f"A autenticidade é sua maior superpotência, {nome}.",
        f"Você é uma obra de arte em constante evolução, {nome}.",
        f"Suas experiências moldam quem você é, {nome}.",
        f"Seu coração compassivo torna o mundo mais bonito, {nome}.",
        f"Sua luz brilha intensamente, {nome}.",
        f"A verdadeira beleza emana de sua autenticidade, {nome}.",
        f"Aprecie o processo de se tornar a melhor versão de si mesmo, {nome}.",
        f"Cada passo que você dá é um passo na direção certa, {nome}.",
        f"Você é digno de todas as coisas boas, {nome}.",
        f"Cada dia é uma nova página em sua história, {nome}.",
        f"A vida é uma jornada incrível, {nome}.",
        f"Você é forte, resiliente e capaz, {nome}.",
        f"Agradeça pelo que você é agora e antecipe o que você se tornará, {nome}.",
        f"Sua presença é um presente para o mundo, {nome}.",
        f"Abrace o processo de crescimento, {nome}.",
        f"Você é capaz de alcançar alturas incríveis, {nome}.",
        f"A vida está cheia de possibilidades, {nome}.",
        f"Você é um ser único e valioso, {nome}.",
        f"A autenticidade é sua maior fortaleza, {nome}.",
        f"Seu coração generoso torna o mundo mais brilhante, {nome}.",
        f"Sua jornada é cheia de potencial, {nome}.",
        f"Você é mais resiliente do que imagina, {nome}.",
        f"A beleza da vida está nas pequenas coisas, {nome}.",
        f"Você é capaz de superar desafios com graça, {nome}.",
        f"A vida é cheia de possibilidades emocionantes, {nome}.",
        f"Acredite em sua força interior, {nome}.",
        f"Sua jornada está cheia de potencial, {nome}.",
        f"Você é mais resiliente do que pensa, {nome}.",
        f"Cada dia é uma nova oportunidade para ser o melhor de si mesmo, {nome}.",
        f"A autenticidade é sua maior superpotência, {nome}.",
        f"Você é uma obra de arte em constante evolução, {nome}.",
        f"Suas experiências moldam quem você é, {nome}.",
        f"Seu coração compassivo torna o mundo mais bonito, {nome}.",
        f"Sua luz brilha intensamente, {nome}.",
        f"A verdadeira beleza emana de sua autenticidade, {nome}.",
        f"Aprecie o processo de se tornar a melhor versão de si mesmo, {nome}.",
        f"Cada passo que você dá é um passo na direção certa, {nome}.",
        f"Você é digno de todas as coisas boas, {nome}.",
        f"Cada dia é uma nova página em sua história, {nome}.",
        f"A vida é uma jornada incrível, {nome}.",
        f"Você é forte, resiliente e capaz, {nome}.",
        f"Agradeça pelo que você é agora e antecipe o que você se tornará, {nome}.",
        f"Sua presença é um presente para o mundo, {nome}.",
        f"Abrace o processo de crescimento, {nome}.",
        f"Você é capaz de alcançar alturas incríveis, {nome}.",
        f"A vida está cheia de possibilidades, {nome}.",
        f"Você é um ser único e valioso, {nome}.",
        f"A autenticidade é sua maior fortaleza, {nome}.",
        f"Seu coração generoso torna o mundo mais brilhante, {nome}.",
        f"Sua jornada é cheia de potencial, {nome}.",
        f"Você é mais resiliente do que imagina, {nome}.",
        f"A beleza da vida está nas pequenas coisas, {nome}.",
        f"Você é capaz de superar desafios com graça, {nome}.",
        f"A vida é cheia de possibilidades emocionantes, {nome}.",
        f"Acredite em sua força interior, {nome}.",
        f"Sua jornada está cheia de potencial, {nome}.",
        f"Você é mais resiliente do que pensa, {nome}.",
        f"Cada dia é uma nova oportunidade para ser o melhor de si mesmo, {nome}.",
        f"A autenticidade é sua maior superpotência, {nome}.",
        f"Você é uma obra de arte em constante evolução, {nome}.",
        f"Suas experiências moldam quem você é, {nome}.",
        f"Seu coração compassivo torna o mundo mais bonito, {nome}.",
    ]
        # Adicione mais mensagens conforme necessário
    
    return random.choice(mensagens_positivas)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/obter_mensagem', methods=['POST'])
def obter_mensagem():
    nome = request.form['nome']
    mensagem = obter_mensagem_positiva(nome)
    return jsonify({'mensagem': mensagem})

if __name__ == '__main__':
    app.run(debug=True)
